### Log in user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "adminPassword"
}

### register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "username": "admin",
  "password": "adminPassword",
  "confirmPassword": "adminPassword",
  "isAdmin": true
}