// USERS
// get all users
GET http://localhost:3000/users

// get one user
GET http://localhost:3001/users/{id}

// register new user
POST http://localhost:3001/auth/register

// log in new user
POST http://localhost:3001/auth/login


// CARDS

// get all cards
GET http://localhost:3001/cards
















// AUCTIONS
// get all auctions
GET http://localhost:3001/auctions

// get one auction
GET http://localhost:3001/auctions/{id}

// create new auction
POST http://localhost:3001/auctions

// edit auction
PUT http://localhost:3001/auctions/{id}

// filter auctions by card Type
GET http://localhost:3001/auctions?type={type}

// filter auctions by rarity
GET http://localhost:3001/auctions?rarity={rarity}

// filter auctions with a price greater than
GET http://localhost:3001/auctions?price=gte:{integer}

// filter auctions with a price less than
GET http://localhost:3001/auctions?price=lte:{integer}

// order auctions by ascending price
GET http://localhost:3001/auctions?sort=price&order=asc

// order auctions by descending price
GET http://localhost:3001/auctions?sort=price&order=desc

// order auctions by ascending publishedDateTime
GET http://localhost:3001/auctions?sort=publishedDateTime&order=asc

// order auctions by decending publishedDateTime
GET http://localhost:3001/auctions?sort=publishedDateTime&order=desc

// order auctions by ascending endDateTime
GET http://localhost:3001/auctions?sort=endDate&order=asc

// order auctions by decending endDate
GET http://localhost:3001/auctions?sort=endDate&order=desc